CXXFLAGS=-I/usr/local/Cellar/freeglut/3.0.0/include/ -I/usr/local/Cellar/sdl2/2.0.9_1/include/SDL2/
LDFLAGS=-L/usr/local/Cellar/freeglut/3.0.0/lib/ -L/usr/local/Cellar/sdl2/2.0.9_1/lib/
LDLIBS= -framework GLUT -framework OpenGL -framework Cocoa
all: triangle
clean:
		rm -f *.o triangle
